### ISSUE TITLE
webscript

### ISSUE THREAD

**Issue by Cakeprogress** [GDVE/Updater#3]
Hello, and where can I find a web script for this launcher?

**Comment by GDVE** [comment]
You can add the web script yourself. I have not published it.

**Comment by Cakeprogress** [comment]
Is there an option to buy a script for this starter, or somehow get it for free?

**Comment by GDVE** [comment]
I have not used a script for the updater. I have implemented the processing of requests from the program through the Spring Framework REST api. 

**UpdatesHandler.class**

`
public class UpdatesHandler {

    private final UpdatesRepo updatesRepo;
    private final RuntimesRepo runtimesRepo;

    public UpdatesHandler(UpdatesRepo updatesRepo, RuntimesRepo runtimesRepo) {
        this.updatesRepo = updatesRepo;
        this.runtimesRepo = runtimesRepo;
    }

    public Object checkUpdates(CheckUpdatesRequest request) {

        Optional<FileInfo> optionalLauncherFileInfo = updatesRepo.getLauncherFileInfo();
        Optional<FileInfo> optionalUpdaterFileInfo = updatesRepo.getUpdaterFileInfo(request.getApplicationFormat());

        if (optionalLauncherFileInfo.isPresent() && optionalUpdaterFileInfo.isPresent()) {
            return new CheckUpdatesResponse(
                    optionalLauncherFileInfo.get(),
                    optionalUpdaterFileInfo.get(),
                    runtimesRepo.findByTypeAndSystem(RuntimeFileInfo.RuntimeType.GAME, request.getSystemId()));
        }

        return new ErrorResponse("Ваша система не поддерживается лаунчером!");
    }
}
`

**UpdatesRepo.class**

`
public class UpdatesRepo extends ThreadSafeRepo<FileInfo> {

    public UpdatesRepo() {
        this.refresh();
    }

    @Override
    protected void collect() {
        Stream<Path> stream;
        try {
            stream = Files.find(Paths.get(ServerConfiguration.RESOURCES_DIR + "/program/"), 1,
                    ((path, attributes) -> {
                        String pathString = path.toString();
                        return attributes.isRegularFile() && (pathString.endsWith(".jar") || pathString.endsWith(".exe"));
                    }));
        } catch (IOException e) {
            logger.error("Неудалось обновить информацию о файлах: {?}", e);
            return;
        }
        stream.forEach(path -> {
            try {
                this.add(new FileInfo(path));
            } catch (IOException e) {
                logger.error("Неудалось обновить информацию о файле: {?}", e);
            }
        });
    }

    public Optional<FileInfo> getLauncherFileInfo() {
        return this.stream().filter(fileInfo -> fileInfo.getName().equals("Launcher.jar")).findAny();
    }

    public Optional<FileInfo> getUpdaterFileInfo(String type) {
        return this.stream().filter(fileInfo -> fileInfo.getName().equals("SimpleMinecraft." + type)).findAny();
    }
}
`

**RuntimesRepo**

`
public class RuntimesRepo extends ThreadSafeRepo<RuntimeFileInfo> {

    public RuntimesRepo() {
        this.refresh();
    }

    @Override
    protected void collect() {
        try {
            Files.find(Paths.get(ServerConfiguration.RESOURCES_DIR + "/runtime/"), Integer.MAX_VALUE,
                    (path, attributes) -> {
                        String pathString = path.toString();
                        return attributes.isRegularFile() && (pathString.endsWith(".tar") || pathString.endsWith(".tar.gz")
                                || pathString.endsWith(".zip"));
                    })
                    .forEach(path -> {
                        try {
                            this.add(new RuntimeFileInfo(path));
                        } catch (IOException e) {
                            logger.error("Неудалось обновить информацию о файле: {?}", e);
                        }
                    });
        } catch (IOException e) {
            logger.error("Неудалось обновить информацию о Java Runtime: {?}", e);
        }
    }

    public List<FileInfo> findByTypeAndSystem(RuntimeType type, String system) {
        return this.stream()
                .filter(runtime -> runtime.getName().contains(system) && runtime.getType().equals(type))
                .collect(Collectors.toList());
    }

    public List<RuntimeFileInfo> findAll() {
        return new ArrayList<>(this);
    }
}
`

**Comment by GDVE** [comment]
FileInfo.class 

public class FileInfo {

    @Getter
    private String path;
    @Getter
    private final String name;
    @Getter
    private final String url;
    @Getter
    private final String md5;
    @Getter
    private final long size;

    public FileInfo(Path path) throws IOException {
        this.md5 = CryptUtils.md5(path);
        this.size = Files.size(path);
        this.url = RESOURCES_URL + path.toUri().getPath().replace(RESOURCES_DIR.toUri().getPath(), "/").replaceAll(" ", "%20") + "?" + this.md5;
        this.path = path.toUri().getPath().replace(RESOURCES_DIR.toUri().getPath(), "/");
        if (this.path.startsWith("/clients/")) this.path = this.path.replace("/clients", "");
        this.name = path.getFileName().toString();
    }
}
